#!/bin/sh
#
# Load all necessary st modules
# 
# chkconfig: S 9 0
#
  
   modprobe cpu_frequ
   echo 31241 > /proc/cpu_frequ/pll0_ndiv_mdiv

   echo "init frontpanel"
   modprobe proton
   modprobe simu_button
   #mknod -m 644 /dev/vfd c 147 0
   #mknod -m 644 /dev/hdmi_cec c 149 0
   modprobe e2_proc

   echo "init stmfb"
   modprobe stmcore-display-stx7109c3
   modprobe stmfb display0=1920x1080-32@50:12m:pal:yuv:yuv

   echo "LOADING MODULES"   
   echo "LOAD" >/dev/vfd

   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init AVS"
   modprobe avs type=stv6418

   modprobe mmelog
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   modprobe pseudocard

   echo "init frontends"
   modprobe fe-core

   echo "init drivers"
   modprobe pti
   modprobe stm_monitor
   modprobe stmsysfs
   modprobe stmdvb

   modprobe player2 discardlateframe=0
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen
   modprobe smartcard debug=100
   modprobe bpamem
   
   echo "init oc"
   #modprobe cpu_frequ
   #300mhz
   echo 15110 > /proc/cpu_frequ/pll0_ndiv_mdiv
   #echo 1 > /proc/cpu_frequ/pll1_fdma_bypass
   #15110 = 266mhz
   #25609 = 300mhz
   #9475 = 333mhz
   #31241 = 366mhz
   #22790 = 400mhz
   #3841 = 405mhz
   #35593 = 417mhz
   #36361 = 426mhz
   #4097 = 432mhz
   rmmod cpu_frequ
   
   echo "1" > /proc/sys/kernel/printk #for more log change level or  remake line 
   cat /etc/videomode > /proc/stb/video/videomode
   showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

	stfbcontrol a 255
	echo " e2 "
