#!/bin/sh
#
# Load all necessary st modules
# 
# chkconfig: S 9 0
#

echo "init frontpanel"
modprobe aotom
modprobe simu_button
#mknod -m 644 /dev/vfd c 147 0
#mknod -m 644 /dev/hdmi_cec c 149 0
modprobe e2_proc

   echo "init stmfb"
   modprobe stmcore-display-sti7105
   modprobe stmfb display0=1280x720-32@50:15m:pal:yuv:yuv

   echo "LOADING MODULES"   
   echo "LOAD" > /dev/vfd

   if [ ! -e /lib/firmware/audio.elf ]; then
      echo "FW MISSING!!!"
   fi
   if [ -e /lib/modules/ics.ko ]; then
      modprobe /lib/modules/ics.ko firmware=1:video.elf,2:audio.elf bpa2_part=LMI_IO
      modprobe /lib/modules/embx.ko
      modprobe /lib/modules/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2
#      modprobe /lib/modules/embxmailbox.ko mailbox0=0xFE211000:136:set2 mailbox1=0xFE212000:137:set2
      modprobe /lib/modules/mme.ko pool_size=524288
      modprobe /lib/modules/mme_user.ko
   else
      /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
   echo "load v firmware"
      /bin/ustslave /dev/st231-0 /lib/firmware/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   modprobe mme_host transport0=shm
   fi

   echo "init AVS"
   modprobe avs type=avs_pio
   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
   echo "init player $player"

   modprobe mmelog
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   modprobe pseudocard
   modprobe spark7162
   modprobe pti waitMS=20 videoMem=4096
   modprobe stmdvb
   modprobe stm_monitor
   modprobe player2 discardlateframe=0
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen
   modprobe smartcard
   modprobe bpamem
   
      # Load module for swap in ram
   mem_by_cpu=$(($(grep MemTotal /proc/meminfo | awk ' { print $2 } ')*256))
   modprobe zram num_devices=1
   echo $mem_by_cpu > /sys/block/zram0/disksize
   
   if [ ! `grep 'hdmicec.enabled=false' /etc/enigma2/settings` ]; then
    modprobe cec
   fi
   echo "1" > /proc/sys/kernel/printk #for more log change level or  remake line
   cat /etc/videomode > /proc/stb/video/videomode
   showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
#   rm -f /dev/sparkid
#   mknod /dev/sparkid c $major 0 

	stfbcontrol a 255

   # Enable swap in ram
   mkswap /dev/zram0
   swapon /dev/zram0

	echo " e2 "

